name: SchematicReplacer
version: ${project.version}
main: me.vphydra.schematicreplacer.SchematicReplacer
api-version: 1.15
authors: [Conor]
description: replaces bending arena
website: https://github.com/CRea7
depend: [WorldEdit]
commands:
  replacer:
    description: schmetic paste
    permission: replacer
    usage: /replacer <World> <X> <Y> <Z> <Schematic Name>